extends RefCounted

var runner: TestRunner


func run() -> void:
	print("\n--- WeatherEffectsSourceTest ---")

	var controller_source := _read_file("res://Scripts/Weather/WeatherEffectsController.gd")
	var scene_source := _read_file("res://Scenes/Weather/WeatherEffects.tscn")
	var main_scene_source := _read_file("res://Scenes/Game/mainScene.tscn")
	var storm_weather_source := _read_file("res://Data/Weather/storm_weather.tres")
	var rain_import_source := _read_file("res://Assets/Audio/Weather/rain_loop.wav.import")
	var storm_import_source := _read_file("res://Assets/Audio/Weather/storm_rain_loop.wav.import")

	runner.assert_true(controller_source.contains("res://Assets/Audio/Weather/rain_loop.wav"), "Rain loop SFX path is wired")
	runner.assert_true(controller_source.contains("res://Assets/Audio/Weather/storm_rain_loop.wav"), "Storm rain loop SFX path is wired")
	runner.assert_true(controller_source.contains("res://Assets/Audio/Weather/thunder.wav"), "Thunder SFX path is wired")
	runner.assert_true(controller_source.contains("const SFX_BUS := \"SFX\""), "Weather SFX use the SFX bus constant")
	runner.assert_true(controller_source.contains("rain_audio.bus = SFX_BUS"), "Rain loop routes through SFX")
	runner.assert_true(controller_source.contains("storm_audio.bus = SFX_BUS"), "Storm loop routes through SFX")
	runner.assert_true(controller_source.contains("thunder_audio.bus = SFX_BUS"), "Thunder routes through SFX")
	runner.assert_true(controller_source.contains("@export var rain_loop_volume_db := 0.0"), "Rain loop does not apply local gain")
	runner.assert_true(controller_source.contains("@export var storm_loop_volume_db := 0.0"), "Storm rain loop does not apply local gain")
	runner.assert_true(controller_source.contains("@export var thunder_volume_db := 0.0"), "Thunder does not apply local gain")
	runner.assert_true(controller_source.contains("@export var debug_weather_effects := false"), "Weather debug prints are disabled by default after final audio regression")
	runner.assert_true(controller_source.contains("@export var cloudy_cloud_alpha := 0.42"), "Cloudy weather has visible cloud intensity")
	runner.assert_true(controller_source.contains("@export var rain_cloud_alpha := 0.58"), "Rain weather has stronger cloud intensity")
	runner.assert_true(controller_source.contains("@export var storm_cloud_alpha := 0.78"), "Storm weather has the strongest cloud intensity")
	runner.assert_true(controller_source.contains("@export var rain_loop_fallback_to_storm_stream := true"), "Rebuilt rain audio can fall back to storm stream only when rain stream is missing")
	runner.assert_true(controller_source.contains("@export var rain_loop_manual_restart := true"), "Rebuilt rain audio can avoid WAV loop import issues")
	runner.assert_true(controller_source.contains("@export var storm_loop_manual_restart := true"), "Rebuilt storm rain audio can avoid WAV loop import issues")
	runner.assert_true(controller_source.contains("WeatherRainLoopRebuiltPlayer"), "Rain audio uses a rebuilt dedicated runtime player")
	runner.assert_true(controller_source.contains("WeatherStormRainLoopRebuiltPlayer"), "Storm rain audio uses a rebuilt dedicated runtime player")
	runner.assert_true(controller_source.contains("Rain SFX rebuilt player created:"), "Rebuilt rain player creation is logged for diagnosis")
	runner.assert_true(controller_source.contains("Storm SFX rebuilt player created:"), "Rebuilt storm rain player creation is logged for diagnosis")
	runner.assert_true(controller_source.contains("Rain SFX rebuilt player uses manual restart loop"), "Rebuilt rain player logs manual restart loop mode")
	runner.assert_true(controller_source.contains("Storm SFX rebuilt player uses manual restart loop"), "Rebuilt storm rain player logs manual restart loop mode")
	runner.assert_true(controller_source.contains("Rain SFX RETRY PLAY on WeatherRainLoopRebuiltPlayer"), "Rebuilt rain player retries playback if Godot stops it immediately")
	runner.assert_true(controller_source.contains("Storm SFX RETRY PLAY on WeatherStormRainLoopRebuiltPlayer"), "Rebuilt storm rain player retries playback if Godot stops it immediately")
	runner.assert_true(controller_source.contains("func _update_rain_audio_watchdog(delta: float) -> void:"), "Rebuilt rain player has a non-frame-spam watchdog")
	runner.assert_true(controller_source.contains("func _update_storm_audio_watchdog(delta: float) -> void:"), "Rebuilt storm rain player has a non-frame-spam watchdog")
	runner.assert_true(controller_source.contains("Rain SFX watchdog restart"), "Rain watchdog restart is logged for diagnosis")
	runner.assert_true(controller_source.contains("Storm SFX watchdog restart"), "Storm watchdog restart is logged for diagnosis")
	runner.assert_true(controller_source.contains("rain_audio.volume_db = rain_loop_volume_db"), "Rain loop applies local gain")
	runner.assert_true(controller_source.contains("storm_audio.volume_db = storm_loop_volume_db"), "Storm loop applies local gain")
	runner.assert_true(controller_source.contains("thunder_audio.volume_db = thunder_volume_db"), "Thunder applies local gain")
	runner.assert_true(controller_source.contains("process_mode = Node.PROCESS_MODE_ALWAYS"), "Weather effects can process while game is paused")
	runner.assert_true(controller_source.contains("rain_audio.process_mode = Node.PROCESS_MODE_ALWAYS"), "Rain audio player can run while paused")
	runner.assert_true(controller_source.contains("storm_audio.process_mode = Node.PROCESS_MODE_ALWAYS"), "Storm audio player can run while paused")
	runner.assert_true(controller_source.contains("thunder_audio.process_mode = Node.PROCESS_MODE_ALWAYS"), "Thunder audio player can run while paused")
	runner.assert_true(not controller_source.contains("WeatherRainRuntimePlayer"), "Old rain runtime player path was removed")
	runner.assert_true(not controller_source.contains("WeatherStormRuntimePlayer"), "Old storm runtime player path was removed")
	runner.assert_true(controller_source.contains("WeatherThunderRuntimePlayer"), "Thunder audio uses a root-level runtime player")
	runner.assert_true(controller_source.contains("get_tree().root.add_child(player)"), "Weather runtime audio players are added to the root viewport")
	runner.assert_true(controller_source.contains("func _exit_tree()"), "Weather runtime audio players are cleaned up when the scene exits")
	runner.assert_true(controller_source.contains("@export var lightning_flash_energy := 5.0"), "Storm lightning has a stronger runtime light")
	runner.assert_true(controller_source.contains("@export var lightning_screen_flash_alpha := 0.28"), "Storm lightning has a visible screen flash")
	runner.assert_true(controller_source.contains("OmniLight3D.new()"), "Storm thunder creates a runtime lightning flash light")
	runner.assert_true(controller_source.contains("CanvasLayer.new()"), "Storm thunder creates a screen-space lightning flash layer")
	runner.assert_true(controller_source.contains("ColorRect.new()"), "Storm thunder creates a screen-space lightning flash overlay")
	runner.assert_true(controller_source.contains("func _trigger_lightning_flash()"), "Thunder can trigger a lightning flash")
	runner.assert_true(controller_source.contains("Lightning flash ON"), "Lightning flash debug print exists")
	runner.assert_true(controller_source.contains("WeatherCloudLayer"), "Weather effects create a runtime cloud layer")
	runner.assert_true(controller_source.contains("SphereMesh.new()"), "Sky clouds use lightweight low-poly sphere puffs")
	runner.assert_true(controller_source.contains("func _set_cloudy_weather()"), "Cloudy weather has a dedicated no-rain visual state")
	runner.assert_true(controller_source.contains("_set_cloud_layer(\"sunny\""), "Sunny weather disables visible clouds")
	runner.assert_true(controller_source.contains("_set_cloud_layer(\"cloudy\""), "Cloudy weather enables sky clouds")
	runner.assert_true(controller_source.contains("_set_cloud_layer(\"rain\""), "Rain weather enables sky clouds")
	runner.assert_true(controller_source.contains("_set_cloud_layer(\"storm\""), "Storm weather enables darker sky clouds")
	runner.assert_true(controller_source.contains("CloudLayer sunny OFF"), "Cloud layer sunny debug print exists")
	runner.assert_true(controller_source.contains("CloudLayer cloudy ON"), "Cloud layer cloudy debug print exists")
	runner.assert_true(controller_source.contains("CloudLayer rain ON"), "Cloud layer rain debug print exists")
	runner.assert_true(controller_source.contains("CloudLayer storm ON"), "Cloud layer storm debug print exists")
	runner.assert_true(controller_source.contains("Cloud intensity: %.2f"), "Cloud intensity debug print exists")

	runner.assert_true(controller_source.contains("WeatherManager.weather_changed.connect"), "Weather effects connect to WeatherManager weather_changed")
	runner.assert_true(controller_source.contains("WeatherManager.current_weather"), "Weather effects read current weather on startup")
	runner.assert_true(controller_source.contains("func apply_current_weather()"), "Weather effects can apply current weather on demand")
	runner.assert_true(controller_source.contains("func apply_weather(weather_value: Variant)"), "Weather effects accept flexible weather values")
	runner.assert_true(controller_source.contains("func _get_weather_key(weather_value: Variant)"), "Weather effects normalize weather values")
	runner.assert_true(controller_source.contains("func _normalize_weather_text(raw_value: String)"), "Weather effects normalize weather names and paths")
	runner.assert_true(controller_source.contains("text.find(\"storm\") != -1"), "Weather normalization recognizes storm names and resource paths")
	runner.assert_true(controller_source.contains("weather_data.resource_path"), "Weather normalization checks resource paths")
	runner.assert_true(controller_source.contains("WeatherData.WeatherType.CLOUDY"), "Cloudy weather state is handled")
	runner.assert_true(controller_source.contains("WeatherData.WeatherType.RAIN"), "Rain weather state is handled")
	runner.assert_true(controller_source.contains("WeatherData.WeatherType.STORM"), "Storm weather state is handled")
	runner.assert_true(storm_weather_source.contains("weather_type = 3"), "storm_weather.tres uses the STORM weather enum")
	runner.assert_true(storm_weather_source.contains("display_name = \"Storm\""), "storm_weather.tres has a storm display name")
	runner.assert_true(controller_source.contains("_set_clear_weather"), "Clear weather disables rain and storm effects")
	runner.assert_true(controller_source.contains("_schedule_next_thunder"), "Thunder is scheduled while storm is active")
	runner.assert_true(controller_source.contains("if _current_weather_key != \"storm\""), "Thunder timer is guarded to storm weather only")
	runner.assert_true(controller_source.contains("randf_range(thunder_min_delay, thunder_max_delay)"), "Thunder timing is randomized")
	runner.assert_true(controller_source.contains("AudioStreamWAV.LOOP_FORWARD"), "Rain and storm loops are configured to loop")
	runner.assert_true(controller_source.contains("AudioStreamWAV.LOOP_DISABLED"), "Rebuilt rain loop can disable WAV looping and use finished-signal replay")
	runner.assert_true(rain_import_source.contains("edit/loop_mode=1"), "Rain loop import is configured for forward looping")
	runner.assert_true(storm_import_source.contains("edit/loop_mode=1"), "Storm loop import is configured for forward looping")
	runner.assert_true(rain_import_source.contains("edit/normalize=true"), "Rain loop import is normalized")
	runner.assert_true(storm_import_source.contains("edit/normalize=true"), "Storm loop import is normalized")
	runner.assert_true(rain_import_source.contains("compress/mode=0"), "Rain loop import uses uncompressed playback")
	runner.assert_true(storm_import_source.contains("compress/mode=0"), "Storm loop import uses uncompressed playback")
	runner.assert_true(controller_source.contains("_on_rebuilt_rain_audio_finished"), "Rebuilt rain loop has a finished-signal fallback")
	runner.assert_true(controller_source.contains("_on_rebuilt_storm_audio_finished"), "Rebuilt storm rain loop has a finished-signal fallback")
	runner.assert_true(controller_source.contains("func _duplicate_stream(stream: AudioStream) -> AudioStream:"), "Weather audio duplicates streams before loop mutation")
	runner.assert_true(not controller_source.contains("UISoundManager.play_water_crop()"), "Weather effects do not call gameplay watering SFX for diagnosis")
	runner.assert_true(not controller_source.contains("UISoundManager.play_weather"), "Weather effects do not route weather loops through UISoundManager")
	runner.assert_true(controller_source.contains("func _verify_loop_playing(player: AudioStreamPlayer)"), "Weather loop playback verifies player state after one frame")
	runner.assert_true(controller_source.contains("Rain SFX RETRY PLAY"), "Rain loop retries playback if Godot stops it immediately")
	runner.assert_true(controller_source.contains("Weather SFX stream loaded:"), "Weather audio load debug print exists")
	runner.assert_true(controller_source.contains("Weather SFX play request:"), "Weather audio bus-state debug print exists")
	runner.assert_true(controller_source.contains("WeatherEffectsController ready"), "Temporary ready debug print exists")
	runner.assert_true(controller_source.contains("WeatherEffects normalized weather: %s"), "Temporary weather normalization debug print exists")
	runner.assert_true(controller_source.contains("WeatherEffects apply storm"), "Temporary storm apply debug print exists")
	runner.assert_true(controller_source.contains("Storm VFX ON"), "Temporary storm VFX debug print exists")
	runner.assert_true(controller_source.contains("Storm SFX PLAY"), "Temporary storm SFX debug print exists")
	runner.assert_true(controller_source.contains("Thunder timer START"), "Temporary thunder timer debug print exists")
	runner.assert_true(controller_source.contains("Thunder PLAY"), "Temporary thunder play debug print exists")
	runner.assert_true(scene_source.contains("RainParticles"), "Weather effects scene contains rain particles")
	runner.assert_true(scene_source.contains("StormParticles"), "Weather effects scene contains storm particles")
	runner.assert_true(scene_source.contains("RainAudio"), "Weather effects scene contains rain audio player")
	runner.assert_true(scene_source.contains("StormRainAudio"), "Weather effects scene contains storm audio player")
	runner.assert_true(scene_source.contains("ThunderAudio"), "Weather effects scene contains thunder audio player")
	runner.assert_true(scene_source.contains("ThunderTimer"), "Weather effects scene contains thunder timer")
	runner.assert_true(scene_source.contains("res://Assets/Audio/Weather/rain_loop.wav"), "Weather effects scene assigns rain loop stream")
	runner.assert_true(scene_source.contains("res://Assets/Audio/Weather/storm_rain_loop.wav"), "Weather effects scene assigns storm loop stream")
	runner.assert_true(scene_source.contains("res://Assets/Audio/Weather/thunder.wav"), "Weather effects scene assigns thunder stream")

	runner.assert_true(main_scene_source.contains("res://Scenes/Weather/WeatherEffects.tscn"), "Gameplay scene instances WeatherEffects")
	runner.assert_true(main_scene_source.contains("follow_target = NodePath(\"../CharacterBody3D\")"), "Weather effects follow the player")


func _read_file(path: String) -> String:
	var file := FileAccess.open(path, FileAccess.READ)

	if file == null:
		return ""

	var text := file.get_as_text()
	file.close()
	return text
